- hosts: localhost

  tasks:
    - import_role:
        name: ubuntu

      tags: ubuntu

    - name: "chrome : Install."

      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

      tags: chrome

    - name: "docker : Install."

      package:
        name: docker.io
        state: present

      tags: docker

    - import_role:
        name: dotnet

      tags: dotnet

    - name: "firefox : Uninstall."

      package:
        name: firefox
        state: absent

      tags: firefox

    - import_role:
        name: git

      tags: git

    - import_role:
        name: neovim

      tags: neovim

    - name: "npm : Install."

      package:
        name: npm
        state: present

      tags: npm

    - name: "prettier : Install."

      community.general.npm:
        global: yes
        name: prettier

      tags: prettier

    - import_role:
        name: rider

      tags: rider
