- hosts: localhost

  tasks:
    - import_role:
        name: ubuntu

      tags: ubuntu

    - name: "docker : Install."

      package:
        name: docker.io
        state: present

      tags: docker

    - import_role:
        name: git

      tags: git

    - name: "java : Install."

      package:
        name: openjdk-11-jdk
        state: present

      tags: java

    - name: "npm : Install."

      package:
        name: npm
        state: present

      tags: npm

    - name: "prettier : Install."

      community.general.npm:
        global: yes
        name: prettier

      tags: prettier

    - name: "visual-studio-code : Install."

      apt:
        deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
