- hosts: localhost

  tasks:
    - import_role:
        name: ubuntu

      tags: ubuntu

    - name: "docker : Install."

      package:
        name: docker.io
        state: present

      tags: docker

    - import_role:
        name: git

      tags: git
