- name: Set APT mirror.

  copy:
    dest: /etc/apt/sources.list
    group: root
    mode: "0664"
    owner: root
    src: files/sources.list

  register: result

- name: Update APT cache.

  apt:
    update_cache: yes

  when: result is changed

- name: Install psutil.

  package:
    name: python3-psutil
    state: present

- name: Apply dconf config.

  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"

  become_user: david

  loop:
    # prettier-ignore
    - { key: "/org/gnome/desktop/interface/clock-format", value: "'12h'" }

    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-1", value: "['<Shift><Super>1']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-2", value: "['<Shift><Super>2']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-3", value: "['<Shift><Super>3']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-4", value: "['<Shift><Super>4']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-5", value: "['<Shift><Super>5']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-6", value: "['<Shift><Super>6']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-7", value: "['<Shift><Super>7']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-8", value: "['<Shift><Super>8']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-9", value: "['<Shift><Super>9']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-10", value: "['<Shift><Super>0']" }

    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1", value: "['<Super>1']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2", value: "['<Super>2']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3", value: "['<Super>3']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4", value: "['<Super>4']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5", value: "['<Super>5']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6", value: "['<Super>6']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7", value: "['<Super>7']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8", value: "['<Super>8']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-9", value: "['<Super>9']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-10", value: "['<Super>0']" }

    - { key: "/org/gnome/desktop/wm/preferences/num-workspaces", value: "10" }

    - { key: "/org/gnome/mutter/dynamic-workspaces", value: "false" }

    - { key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed", value: "false" }

    - { key: "/org/gnome/shell/extensions/dash-to-dock/hot-keys", value: "false" }

    - { key: "/org/gnome/shell/keybindings/switch-to-application-1", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-2", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-3", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-4", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-5", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-6", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-7", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-8", value: "@as []" }
    - { key: "/org/gnome/shell/keybindings/switch-to-application-9", value: "@as []" }

- name: Set timezone.

  community.general.timezone:
    name: America/New_York
